# Generated by Django 3.2.2 on 2023-06-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksinfo',
            name='Bookstime',
            field=models.CharField(max_length=16, verbose_name='出版日期'),
        ),
    ]
