# Generated by Django 3.2.18 on 2023-06-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BooksInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Booksname', models.CharField(max_length=16, verbose_name='书籍名')),
                ('Bookstime', models.CharField(max_length=16, verbose_name='出版时间')),
                
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
            ],
        ),
    ]
